### ISSUE TITLE
Improve Documentation by adding explanations and examples

### ISSUE THREAD

**Issue by domis4** [blue-prism/ms-excel-utility#2]
First, thanks for this lovely crafted Object. It is very benefitial in my everyday use. I do have a suggestion though, that might improve it for others too.
## IS

As a developer you can't distinguish the difference between "Close All Instances" and "Exit" by the Action Names itself. Looking the (docx) documentation up, is not helpful. The current documentation is a list of actions that are contained in the Business Object. You need to open the Business Object to look up what this action does, which is time consuming

## SHOULD

A short explanation what every action does with a simple example would benefit the developer alot.

**Comment by EricWilson-BluePrism** [comment]
Hi @domis4,

I apologize for the delay in responding to this. You are absolutely correct, the current documentation for this VBO is pretty bad. FWIW, there is an extended version of the Excel VBO available in another repos which also includes slightly better documentation. You can find that PDF here: 

https://github.com/blue-prism/MSExcelVBO_Extended/blob/master/MS%20Excel%20VBO%20(Extended)%20-%20User%20Guide.pdf

We'll try to copy that documentation over to this VBO to replace the existing doc.
