### ISSUE TITLE
Find Next Empty Cell slow with large datasets

### ISSUE THREAD

**Issue by AmaliaKalio** [blue-prism/ms-excel-utility#7]
When working with a dataset of 40k+ rows, I found that this was taking around 5-6 minutes. The system was a quad 2.1 with 16GB of RAM, but nothing was close to being maxed out.

Resolved by replacing the loop at the end with the following code, and supplying an additional input parameter of a starting cell. Operation took 1-2 seconds.

```
if dirn = -4162 or dirn = -4121
	excel.Range(startCell).End(dirn).Offset(1,0).Select
else
	excel.Range(startCell).End(dirn).Offset(0,1).Select
end if
cellref = excel.ActiveCell.Address(False,False)
```

**Comment by EricWilson-BluePrism** [comment]
After further investigation it's been determined this solution only delivers consistent results when performing a Down search. Up, Left, and Right can be problematic, so we are not going to implement this change at this time. If MS improve the interop library between .NET and Excel we may revisit this.
